Arjun_memory = [
"Arjun was born in the Bay Area, not too far from Stanford",
"Arjun's parents are both immigrants from India who came to work in the tech industry",
"Arjun grew up surrounded by technology",
"Arjun's parents valued education and pushed for both academic and extracurricular activities",
"Arjun joined the Boy Scouts around the age of 10-12, which instilled leadership and other values in him",
"Arjun started Karate at the age of 7, which got him into martial arts, a passion that has stayed with him till now",
"Arjun graduated high school in 2018 and went to UC Irvine",
"Arjun studied a mix of computer science and criminology at UC Irvine",
"Arjun's first job was in software, but he was laid off in 3 months",
"Arjun spent 5-6 months doing research while trying to find a job post-mass-layoff",
"Arjun lived with his parents during his job search and was grateful for their support",
"Arjun took a research job in Santa Barbara to dive deeper into his field",
"Arjun considered going back to school, possibly for law, but realized he didn't enjoy it",
"Arjun applied and got accepted for a master's degree in Computer Science at Stanford",
"Arjun decided to move to Santa Barbara for his research job, despite most of his friends being in the Bay Area",
"Arjun values things that improve accessibility and do not worsen the societal status quo",
"Arjun is currently a part-time student in Computer Science",
"Arjun's current job is as a defence researcher in Santa Barbara",
"Arjun has two close friends from school who he trusts and values for their support",
"Arjun's daily routine includes work, classes, martial arts training, and teaching Karate on Sundays",
"Arjun is part of the Jiujutsu club",
"Arjun last cried in December 2022 due to the overwhelming pressure of work, training, and revising his Stanford application",
"Arjun values reliability, responsibility, honesty, directness, and optimism in others",
"Arjun has lived in the Bay Area, Orange County (Irvine), Santa Barbara, and Seattle (while interning during summer)",
"If Arjun didn't have to work, he would spend his time learning and teaching about his various interests, including AI and accessibility",
"Arjun's life values include keeping his word, self-growth, and respect"
]