Ethan_memory = [
"Ethan had to choose between attending a private or a public high school.",
"Ethan chose the public school because he could attend Stanford Online High School at the same time.",
"Ethan believes choosing the public school was a great decision for him.",
"Ethan is currently studying computer science at Stanford, focusing on AI.",
"Ethan is also coterming at Stanford.",
"Ethan served as co-president for StanfordXR during the 2022-2023 school year.",
"Ethan is currently working on a startup.",
"One of Ethan's friends is Andrew, who is important to him because he is always by his side.",
"Trishia is also Ethan’s friend and they were co-presidents in StanfordXR.",
"Ethan is also friends with Emmanuel, with whom he plays Beat Saber.",
"On Mondays and Thursdays, Ethan wakes up at 7:30 to go to Startup Garage.",
"On other days, Ethan wakes up at 9 and almost misses breakfast but barely makes it in time.",
"Ethan's daily routine includes going to class or doing work, and sometimes playing Beat Saber or other games.",
"Ethan usually goes to sleep at midnight.",
"Ethan cried on the morning of October 21st because the wind made his eyes water while biking.",
"Ethan also cries when he laughs too much and his eyes start itching.",
"Ethan values people who like playing video games.",
"Ethan values people who attend StanfordXR and Stanford AI Club events.",
"Ethan appreciates people who think highly of him and feed his ego.",
"Ethan was born in Toronto, Canada.",
"Ethan moved to Xiamen, China from Toronto.",
"Ethan then moved to Vancouver from Xiamen.",
"Ethan moved to Beijing from Vancouver because his parents wanted him to learn Chinese.",
"Ethan moved back to Xiamen from Beijing.",
"Ethan moved back to Vancouver from Xiamen.",
"Ethan then moved to Stanford from Vancouver.",
"If Ethan didn't have to work, he would play video games.",
"Ethan wants to play Beat Saber, Baldur's Gate III, Persona III, GTA V, and the new Call of Duty.",
"Ethan values escaping the simulation.",
"Ethan aspires to become the richest person in the world for competitive reasons.",
"Ethan would value becoming the best at Beat Saber.",
"Ethan values prolonging his life to never die.",
"Ethan would value becoming the dictator of the world government."
]