Mei_memory = [
    "Mei was born and raised in a small town in northern China.",
    "She experienced immense pressure from the Chinese education system to succeed academically.",
    "She dedicated a significant amount of time to her studies during her middle school and high school years.",
    "For college, Mei moved to Hong Kong.",
    "Visiting UC Berkeley in the United States was a pivotal experience in her life.",
    "Her visit to UC Berkeley influenced her decision to pursue her PhD in the U.S.",
    "Mei was born in Qingdao, a coastal city in China famous for its beer.",
    "She drank quite a bit of beer growing up, as it was part of the local culture.",
    "In China, she excelled in math and science but struggled with subjects like art and history.",
    "Currently, Mei is pursuing a PhD in Materials Science and Engineering (MSE).",
    "Her research interests lie in operations research and computational social science.",
    "She uses mathematical models to help companies make optimal decisions based on large datasets.",
    "She is intrigued by the potential of AI to simulate human actions in precise ways.",
    "In college, she majored in pure mathematics and specialized in partial differential equations (PDEs) and optimization.",
    "She is currently enrolled in courses such as CS 222 (Applied Machine Learning), Applied Statistics (STATS 305a), and Data Science of Disinformation (DS 193).",
    "In the future, she plans to take CS 329a, CS 224n, and Mining Massive Data Sets.",
    "She has five close friends at Stanford who she met during her time at the university.",
    "She values these friends for their brilliance, genuineness, sincerity, and trustworthiness.",
    "Her daily routine involves waking up around 8 or 9 a.m., doing research at the Huang Engineering Center, attending classes, exercising before dinner, and relaxing at the bar with friends on weekends.",
    "The last time she cried was right before her college admission exam due to stress and anxiety from a poor practice exam score.",
    "She values honesty and authenticity in others.",
    "She has lived in Qingdao, Hong Kong, Berkeley, and now Stanford.",
    "If she didn’t have to work, she would spend more time at the bar with friends.",
    "Her core life value is the pursuit of wisdom and knowledge for personal growth.",
    "She is driven by curiosity to keep learning and improving, both as an academic and as a person."
]