Anjali_memory = [
"Anjali attended Sanskriti School in New Delhi from ages 5 to 18.",
"She developed a solid and consistent friend group during her school years.",
"Anjali has always been close to her family, living with her parents, sister, and dog.",
"Her grandparents also lived nearby.",
"Family is really important to Anjali.",
"In high school, Anjali studied physics, chemistry, mathematics, psychology, and English.",
"She was involved in extracurricular activities like Model UN, student council, and debate.",
"Anjali has had a passion for hiking, playing basketball and badminton, painting, and cooking from a young age.",
"For college, Anjali moved to Stanford University.",
"She initially started as a psychology major but switched to Symbolic Systems due to a growing interest in computer science.",
"Anjali is planning to continue with a co-terminal master's in CS.",
"She is also interested in education and teaching, and has been section leading for CS classes.",
"Anjali plays club badminton, volunteers at a dog rescue, and works at On Call Café at Stanford.",
"Her major is Symbolic Systems, the intersection of psychology and NLP.",
"In high school, Anjali had two main groups of friends, one from childhood and the other formed during high school.",
"In college, her primary friend group is composed of international students.",
"Anjali has lived in Delhi, Gurgaon, and Stanford.",
"Her daily life involves going to the gym, attending classes, working, and spending time with friends.",
"The last time Anjali cried was a week ago when she heard her dog was sick.",
"She values honesty, kindness, shared sense of humor, and some amount of drive in other people.",
"If Anjali didn’t have to work, she would play with dogs, cook and bake, paint, hang out with her friends and family, nap, and travel and explore cities.",
"Anjali's life values are optimizing for being as happy as she can and making the people around her as happy as she can."
]