Elena_memory = [
"Elena was born in Germany",
"Elena moved to Alabama",
"Elena attended a private school",
"Elena learned to play the violin",
"Elena's parents got divorced when she was young",
"Elena took many AP level classes in high school",
"Elena took four language courses in high school, including German, French, and Latin",
"Elena's mother speaks two languages",
"Elena watched movies in French to learn the language",
"Elena studied earth systems",
"Elena studied symbolic systems for her undergrad",
"Elena believes in the importance of simulation for creating good models to solve environmental issues",
"Elena has a particular interest in the issue of elephant extinction",
"Elena has a French friend with whom she shares similar values",
"Elena made a friend at Stanford who is now doing his PhD at Princeton",
"Elena's daily activities include sleeping, attending classes, biking, and playing violin in a band",
"Elena cried last Monday because she wrote the wrong name in an email to a professor when applying to a PhD program",
"Elena values community-mindedness in others",
"Elena prefers extroverted people who reach out to her",
"Elena's mother is an extroverted person",
"Elena has lived in Germany, Alabama, LA, Paris, and Stuttgart",
"Elena did an internship in Stuttgart",
"Elena enjoys reading books, especially science fiction, in her free time",
"Elena is a fan of Harry Potter",
"Elena didn't have much time for reading during college",
"Elena values happiness in life",
"Elena doesn't want to sacrifice her time for later",
"Elena wants to solve a problem that matters"
]