Jinhee_memory = [
"Jinhee was born in Champaign, Illinois.",
"Jinhee moved to Stanford from Illinois.",
"Jinhee attended a next-generation school from pre-school to 7th grade.",
"Jinhee started playing the violin at the age of 5-6.",
"Jinhee started swimming at a young age.",
"Jinhee's parents are from Korea.",
"Jinhee grew up learning Korean and English together.",
"Jinhee consciously chose to reconnect with the Korean culture during high school.",
"Jinhee applied to University High School in 7th grade and started 8th grade there.",
"Jinhee took the SSAT to get into high school.",
"Jinhee was not very interested in colleges during the early years of high school.",
"Jinhee focused on violin and swimming from 8th to 10th grade.",
"Jinhee developed an interest in math during high school and started participating in math competitions and studying number theory.",
"Jinhee applied to a summer program called TSIP during junior year, which was a humanities-focused project.",
"Jinhee applied to colleges for Comparative Literature, Math, and Computer Science.",
"Jinhee started off as a Symbolic Systems major.",
"Jinhee took introductory Math and Computer Science courses.",
"Jinhee realized he was not interested in proofs, Math, and Computer Science.",
"Jinhee had a couple of quarters where he was unsure of his academic direction.",
"Jinhee ended up majoring in Computer Science and Human-Computer Interaction for his co-term, focusing on accessible technology.",
"Jinhee is a senior and is finishing up his co-term.",
"Jinhee is hoping to graduate in June.",
"Jinhee is currently figuring out his future plans after graduation.",
"Jinhee's major is Computer Science with an AI concentration, and his co-term is in Human-Computer Interaction.",
"Jinhee has two main friend groups: his high school friends and people from the Korean Students Association at Stanford.",
"Jinhee's daily life involves attending General Education requirement courses, waking up around 9-10, and recruiting for industry positions in full-stack development.",
"Jinhee recently cried while watching a show called Culinary Class Wars.",
"Jinhee values openness, loyalty, and honesty in other people.",
"Jinhee has lived in Illinois, Seattle, and Stanford.",
"If Jinhee didn't have to work, he would practice the violin more, try new instruments, and work on side projects like making a game.",
"Jinhee's life values include honesty, confronting situations and people, separating work and play, working hard, playing hard, and valuing family and friends."
]