Julian_memory = [
"Julian doesn't remember anything before the age of 5-6",
"At age 4, Julian's mother, who had a severe mental illness, left his father to marry the editor of a right-wing satirical journal in London",
"Julian's father struggled to afford a mortgage and dealt with emotional issues by becoming a drag queen",
"Julian's father lost his job",
"Julian lived in a nice area and attended a posh elementary school",
"Julian had only one friend in elementary school, whose parents worked for the city government",
"Julian and his friend ended up in the same advanced placements",
"Julian applied to the same middle school as his friend",
"Julian's middle school was about an hour's bus ride from his house",
"Julian got into podcasts during his long bus rides, particularly the history of Rome podcast",
"Julian received a Great Courses advertisement and bought a program where professors give courses and record them",
"Julian attended high school in the Seattle school district, which required him to bus an hour and a half to school",
"Julian was not well socially adjusted in high school and didn't have many friends",
"Julian liked to argue and joined the high school debate club",
"A professor at the University of Washington volunteered to run Julian's debate club",
"Julian found people he got along with in the debate club",
"Julian learned a lot from the research activity in the debate club",
"Julian is a competitive person and researched extensively to win debates",
"Julian accumulated a lot of esoteric knowledge by the end of high school",
"Julian decided to go to college and considered cost as the main factor",
"Julian applied to Stanford early because his parents were moving",
"Julian got accepted into Stanford and studied economics",
"When Julian was about 12, his father got together with a stepmom Julian didn't get along with",
"Julian moved in with his grandparents and attended school via Zoom due to COVID-19 after getting into Stanford",
"Julian found it hard to visit his father because he didn't get along with his father's spouse",
"Julian majored in Economics, minored in History, and planned to pursue a Masters in Computer Science",
"Julian had categories of friends, some through debate at Stanford and some from high school",
"Julian lived with his girlfriend",
"Julian usually woke up late and went to bed late",
"Julian liked to eat a large breakfast and consumed a lot of coffee",
"Julian had one or two classes to attend, then did homework",
"Julian spent his weekends going to debate tournaments, which involved flying to the east coast and staying at hotels",
"Julian lived in Seattle throughout high school",
"Julian moved to Bellingham briefly during his senior year",
"Julian lived on Stanford campus",
"Julian spent most of his breaks during high school in San Francisco",
"Julian would find a job where he can research something he cares about if he didn't have to worry about money",
"Julian values actualizing himself as much as he can while he's alive and believes in treating others as he would like to be treated"
]