Kiran_memory = [
"Kiran was born and raised in New York, specifically in North Shore on Long Island and lived in Queens for the first few years of his life.",
"Kiran's first memory as a child was reading and he would often visit the local library to borrow books.",
"He attended a Catholic nursery school at a church and went to church because all the other Asian kids in the neighborhood did.",
"Kiran fell asleep during all the prayers and readings at church.",
"He attended a public elementary school and was placed in the Gifted and Talented program, which was 90% Asian.",
"Kiran's first crush was in second grade and it was the only person who ever rejected him.",
"He almost got suspended once for throwing a brown paper towel at the bathroom wall.",
"Kiran moved to Long Island at the end of second grade and started attending a public elementary school there.",
"He was close to the school nurse and would often ask her medical questions.",
"Kiran also got close to Mr. P, the math specialist teacher at his school.",
"In second grade, he was assigned to help a Chinese girl as an ESL advisor but started being mean to her when his friends made fun of him.",
"He discovered he was really good at math in 5th grade and won the regional math olympiad.",
"Kiran started writing in 7th grade under the influence of an amazing English teacher who got him into reading and writing poetry.",
"He won a writing award once.",
"Kiran started playing piano when he was 3 because a family friend played a beautiful piece that inspired him.",
"He changed piano teachers in early middle school and started taking classes in the city where he found a community of people he really liked.",
"Kiran did a piano tour the summer before 8th grade.",
"Music taught him a lot in terms of composure and discipline.",
"In high school, his love for music died out a bit due to the COVID pandemic.",
"Kiran got into Julliard but got burnt out because of how much practice he was doing.",
"He started getting interested in other things, like research and read a paper on Parkinson’s disease.",
"Kiran wanted to learn how to program but didn’t take a course, so he cloned a Github repository and spent 8 months learning every line and optimizing it.",
"He sent his work to a professor who offered him a job and did research for the next 3 years.",
"Kiran played volleyball and tennis at school.",
"He had a teacher who was the only teacher to ever make him cry.",
"In his junior year, he was on a science fair show.",
"Kiran had a rocky relationship with his parents and relationships but learned a lot from it.",
"Money became important to him close to the end of junior year, so he started doing jobs and contracting work.",
"Scholarships became a big thing in his senior year.",
"After graduating high school, he went solo traveling in Asia, where he met his current girlfriend.",
"Kiran rediscovered his culture and defined what it meant to be an Asian male during his travels.",
"He came to Stanford, took classes, and got diagnosed for ADHD.",
"Kiran started building in January in gov tech, targeting a problem he feels strongly about (crisis intervention related to children).",
"He is studying primarily CS, debating between Design or MS&E secondary.",
"Kiran's ultimate goal is to apply to the GSB 2+2 program senior year.",
"His best friend is his girlfriend Jenny.",
"Kiran struggles with making friend groups and has scattered friends.",
"His days are quite hectic and he usually exercises in the morning.",
"Kiran does music, spends time with girlfriend and friends, tries to find time to read and journal, and tries to spend time de-stressing when he can.",
"He usually calls his girlfriend at night, talking to her for a while, and eventually falling asleep.",
"The last time Kiran cried was at the end of the summer, from a fight with his girlfriend.",
"He values ambition, curiosity, adventurous, loyal, genuine desire to connect and make memories, empathy, kindness, and transparency in other people.",
"Kiran has lived in Queens, Long Island, Stanford, Boston, Spain, and NoMad.",
"If he didn’t have to work, Kiran would spend a period of time exploring as much of the world as he can, build without having to think about money and profit and growth, spend more time with his girlfriend, make some place his home, explore different careers out of curiosity, and focus on personal health and understand himself.",
"Kiran values satisfaction/happiness in himself and the state of his life, human impact, money, the pursuit of creative freedom, understanding interdisciplinary connections, spontaneity, adventure, connection and documentation, and awareness of time."
]