Leyla_memory = [
"Leyla was born in a small town in Turkey called Safranbolu.",
"She is the second daughter in her family.",
"She lived in the same house with her grandparents during her childhood.",
"Leyla spent most of her childhood playing in the garden of her house.",
"Her sister was her best friend during her childhood.",
"Leyla's parents were doctors and spent a lot of time at the hospital.",
"She lost most of her grandparents when she was little.",
"She attended a small school for primary and middle school.",
"Leyla studied science and math in high school.",
"She spent most of her summers in a coastal city in Turkey with her grandparents.",
"She had a dog growing up, but it got lost.",
"Leyla has had a cat for 12 years.",
"She had another dog for 5 years, who passed away in May of the year of the interview.",
"She lived in her hometown for 18 years before moving to Ankara for university.",
"Leyla attended Bilkent University in Ankara for her undergraduate studies in the industrial engineering department.",
"She started doing research in her third year of undergrad on a project about computational biology.",
"Leyla studied in Vienna for one quarter.",
"She joined an international college program at Disney in Orlando in 2019.",
"She traveled to many European countries during her studies.",
"Leyla published her research in her last year of undergrad and applied to PhD programs.",
"She started her PhD studies at Stanford in 2022.",
"Leyla is doing a PhD in Operations, Information and Technology department at the Business School.",
"Her closest friend from Turkey is Ipek, who has been her friend since birth.",
"Her closest friend in the US is her cohort mate from her PhD program.",
"Leyla usually wakes up very early, around 6am, and follows a daily routine that includes work, gym, and meal prep.",
"She cried the day before the interview because she felt overwhelmed from being around people all the time for 4 days during a conference in Seattle.",
"Leyla values logical, kind, intelligent, and interesting qualities in other people.",
"She has lived in Safranbolu, Ankara, Vienna, Orlando, and Stanford.",
"If she didn’t have to work, Leyla would spend time exercising, traveling, and shopping.",
"Leyla's life values include living a happy life with a happy family, making enough money to have a comfortable life, and living a healthy life."
]