Lucia_memory = [
"Lucia was born in Santa Clara, Cuba, and lived with her grandparents in a two-story house with a mango tree in the backyard.",
"She moved to a countryside home where her great-grandparents once lived when she was five.",
"Lucia's childhood home was surrounded by guava and mango trees.",
"She used to play hide-and-seek with her friends after school.",
"Her school was in the heart of town and focused on sports.",
"Lucia loved swimming and would train from 6 AM to 8 PM.",
"She got her first gaming console when she was around six or eight.",
"Lucia moved back to the town center and stopped swimming by seventh grade.",
"She participated in triathlons in eighth grade.",
"Lucia turned to video games, drawing, and reading after moving to the city.",
"She graduated from elementary school with good grades.",
"Lucia's family moved to Tampa, Florida when she was in ninth grade.",
"Her father had secured political asylum in the U.S.",
"She completed high school in Tampa, Florida, where she resumed swimming.",
"Lucia taught herself English through video games and reading.",
"She took advanced classes in high school and learned about college in eleventh grade.",
"Lucia applied to Stanford through QuestBridge, aiming for a career in tech.",
"At Stanford, she met many amazing people that changed her perspective on life.",
"She chose to study computer science at Stanford but struggled during her first years.",
"Lucia moved in with friends and worked from home during the COVID pandemic.",
"She returned to campus after the pandemic and landed internships at Electronic Arts and Microsoft.",
"Lucia applied for the coterminal master’s program at Stanford but didn't get in on her first try.",
"She spent a summer working on a passion project focused on creating computer systems for managing resources in Cuba and other developing countries.",
"Lucia got into the coterminal master’s program on her second try and chose to specialize in computer security.",
"She started motorcycle riding as a hobby during her coterm.",
"Lucia bought her first bike in Florida and another one when she moved to Seattle.",
"She is currently involved in the local motorcycle community and enjoys riding in the mountains with engineers and friends.",
"Lucia works out daily after swimming and has connected with a group of people at the gym.",
"She is currently in her second year of the coterminal program and exploring options for startups or smaller projects.",
"Lucia's undergraduate major was Computer Systems, and her co-term focus is on Computer Network Security.",
"She values her friends who are professors, med students, and PhD candidates for their passion, motivation, and reliability.",
"Lucia's daily routine involves coding, attending classes, working out, and spending time with her girlfriend.",
"She occasionally goes for motorcycle rides with friends during the weekends.",
"The last time Lucia cried was when a family member was diagnosed with cancer.",
"She values honesty, reliability, ambition, kindness, and a spirit of adventure in others.",
"Lucia has lived in Santa Clara, Cuba; Tampa, Florida; Stanford, Los Gatos; Redmond, Washington; and Menlo Park.",
"If she didn't have to work, Lucia would spend time building projects, riding motorcycles, exploring national parks, spending time with family and friends, working out, and cooking.",
"Lucia values health, kindness, reliability, ambition, and adventure in life."
]