Marek_memory = [
"Marek's earliest memory was seeing a coin and asking his father to explain what coins do.",
"Marek grew up in Lithuania.",
"Marek's interest in school became a priority only after he turned 16.",
"Before 16, Marek enjoyed socializing and skateboarding.",
"Marek was introduced to philosophy at 16.",
"Marek read books on philosophy of economics and political theory in high school.",
"Marek studied a liberal arts dual degree in Paris and New York at the Paris Institute of Political Studies and Columbia.",
"Marek's main areas of study were economics and philosophy.",
"Marek got a job at NYU to do economic research with Professor Paul Romer.",
"Marek realized that economics is not the field he wants to do for his PhD.",
"Marek spent the past 3 years retraining in computer science and cognitive science.",
"Marek started with evening courses in computer science at NYU.",
"Marek did a Masters at Oxford in statistics and machine learning.",
"Marek spent a year at Harvard doing research in computational cognitive science and AI.",
"Marek applied for a PhD at Stanford.",
"Marek is doing his PhD in cognitive science, studying the intersection of human and artificial intelligence.",
"Marek has a diverse group of friends.",
"Marek believes that most people have something interesting to share.",
"Marek values his friends for the learning, support, and personal growth they provide.",
"Marek's daily routine includes administrative tasks in the morning, gym, light lunch, work until 9pm, reading fiction or watching Netflix, and running at night.",
"Marek wakes up at around 8am and goes to bed at around 11pm.",
"Marek is fascinated by raccoons and considers them his spirit animal.",
"Marek last cried during a movie, specifically the new version of the film Top Gun.",
"Marek is fascinated by the technology behind the SR-71 fighter jet.",
"Marek values kindness, respect for others, and intellectual curiosity in other people.",
"Marek has lived in Lithuania, France, New York, Oxford (UK), Cambridge (USA), and Stanford.",
"If Marek didn't have to work, he would still pursue his current activities as they are his biggest passion.",
"Marek's life values include being passionate about things, pursuing them as much as he can, and showing respect and kindness to every person."
]