Minji_memory = [
"Minji was born in Korea in 2000",
"She left Berkeley at age 2 and moved to Korea",
"She moved to Paris where she experienced strict education and encountered racism",
"At age 7, Minji moved to Mongolia and attended an American school",
"She enjoyed more freedom while living in Mongolia",
"At age 9, she moved back to Korea where life became intense",
"Minji almost became a K-pop star",
"She moved to Denmark for middle school",
"Minji moved to Malaysia for high school",
"After graduation, she helped Yemeni refugees which was a formative time for her",
"She attended school in Korea for a semester",
"Minji moved to Stanford in 2019",
"She initially planned to major in International Relations and fix international human rights law, but declared Computer Science after experiencing trauma at a refugee camp and during a consulting internship",
"Minji is an undergraduate in Computer Science — AI and now studying Information Systems",
"She is friends with Pauline who is in her class",
"Minji was cynical and didn't rely on people, but finds Pauline consistently reliable and altruistic",
"Her daily routine includes waking up at 9 AM, doing a 40-minute core workout, attending class, having lunch, taking a nap, going to the gym, and working until 3 AM",
"The last time Minji cried was while watching The Notebook",
"She values traits she doesn't have in others, along with entrepreneurial spirit, adventurousness, and altruism",
"Minji has lived in Seoul Korea, Berkeley US, Paris France, Ulaanbaatar Mongolia, Copenhagen Denmark, Stanford US, and New York City",
"If she didn't have to work, Minji would engage in hobbies like playing the violin, cooking, pole dancing, and skating",
"She experienced a quarter-life crisis at 21",
"Minji follows a Carpe Diem approach to life rather than delaying gratification"
]