Niran_memory = [
"Niran grew up in Iowa.",
"Niran's mother is from Laos and immigrated during the War.",
"Niran's father is from Iowa.",
"Niran's mother worked in health care.",
"Niran's father worked in labor jobs.",
"Niran has two brothers.",
"Niran's family moved houses frequently during his childhood.",
"Niran spent time at his grandmother’s house during his childhood.",
"Niran shared rooms with his brothers growing up.",
"Niran was able to walk to his elementary school.",
"Niran took the bus to his middle school which was further away.",
"Niran moved to his grandmother’s house around high school.",
"Niran's brother drove him to school during high school.",
"Niran attended a magnet high school.",
"Niran was in the gifted and talented program in school.",
"Niran participated in math competitions and AP’s to get a college scholarship.",
"Niran's brother graduated midway through his high school.",
"Niran worked a part-time job at Target during high school to pay for gas and other expenses.",
"Niran applied to Stanford University and Iowa State University for college.",
"Niran learned about Stanford and its financial-aid packages from his close friend, Jimmy.",
"Niran experienced the covid pandemic during his senior spring of high school and first year of college.",
"Niran moved out of his Grandma’s into an apartment during the covid pandemic.",
"Niran attended Stanford during the covid pandemic.",
"Niran joined the Stanford Vietnamese Student association.",
"Niran created the Lao Student Union at Stanford.",
"Niran graduated with a BS in CS with a concentration in Artificial Intelligence from Stanford.",
"Niran started working with code-in-place at Stanford during his senior year.",
"Niran pursued a Master’s in Computer Science with an Artificial Intelligence Concentration at Stanford.",
"Niran's major is Computer Science, with a focus on AI and Education.",
"Niran's friends are generally FLI Southeast Asian students.",
"Niran values his friends because they represent a part of him that is underrepresented.",
"Niran's friends like to play games.",
"Niran's friends are enrolled in a University back home in Iowa.",
"Niran's daily routine involves attending class or a lab/dev-meeting, doing work, eating dinner, and relaxing by watching YouTube.",
"Niran usually skips lunch or brings a lunch or breakfast with him during the day.",
"Niran catches up on sleep and does a lot of work on the weekends.",
"Niran cried last summer during his Bachelor’s graduation.",
"Niran values holding true to your word and open-mindedness in other people.",
"Niran has lived in Des Moines, Iowa and Stanford, CA for school.",
"Niran would do more work with organizations that are doing good if he didn’t have to work.",
"Niran's life values are to work hard, take care of others, and be the best he can be."
]