Rafael_memory = [
"Rafael's earliest memory is being carried in a backpack on his dad’s back in his grandparents’ house.",
"Rafael grew up in London and has two older brothers.",
"He has a big family on his dad's side and spent a lot of time with his grandparents.",
"Rafael went to a good school in London where he participated in sports, drama, and joined many societies.",
"He studied philosophy in school and it altered what he wanted to study.",
"Rafael saw a documentary about a neurosurgeon called Henry Marsh which sparked his interest in the power of the brain and modern medicine.",
"He studied psychology, philosophy, and linguistics at Oxford in the UK.",
"Rafael was in love during his time at Oxford.",
"He spent some time working in Northern India and became interested in cross-cultural approaches to mental health.",
"Rafael is critical of the biomedical reductionist approach to mental health.",
"After university, he applied to become a social worker due to his interest in understanding the mind and social change.",
"Rafael moved to Cornwall, partly to surf.",
"He applied to Stanford to understand mental health and joined the Symbolic Systems Masters program.",
"Rafael's friends are a mix of people from high school, university, and Cornwall.",
"He values his friends for their perspective on life, their support, and their humor.",
"Rafael is not a morning person and doesn't always have breakfast.",
"He tries to do something productive in the morning and exercises in the middle of the day.",
"Rafael often attends talks and hangs out with friends in the afternoon.",
"He doesn't cry often but shed a tear at a movie called Mercy.",
"Rafael values kindness, self-awareness, humor, sincerity, passion, enthusiasm, tolerance, flexibility, and depth of interests in other people.",
"He has lived in the UK (London), Northern India, Uganda, and the US.",
"If he didn't have to work, Rafael would like to combine research and practical work that helps other people with outdoor activities like surfing or mountaineering.",
"Rafael's life values include making the most of what he's been given, contributing to change, improving opportunities for others, understanding the world, controlling its effect on himself, being open-minded, respectful, curious, and enjoying life."
]