Riya_memory = [
"Riya is an only child and grew up in Los Angeles.",
"She has lived in the same house her whole life.",
"Riya attended a small elementary school with around 30 people in each grade.",
"She was elected school president in her elementary school.",
"Riya attended a Catholic middle school despite not being Catholic.",
"She met her two best friends on the first day of middle school.",
"Riya joined the Mock Trial and Debate team in 8th grade.",
"She continued to participate in debate throughout high school.",
"Riya decided to attend Brown University for her undergraduate studies.",
"She discovered her passion for computer science at Brown University.",
"Riya is currently pursuing a Master's in Computer Science.",
"She has five close friends from middle school and high school.",
"Riya has about twenty friends from her undergraduate studies at Brown University.",
"She lived with three roommates for two years during her undergraduate studies.",
"At Stanford, she has around twenty friends but only considers a handful her closest.",
"Riya's daily routine involves attending classes/meetings, working on her research project, and winding down with a TV show or TikTok.",
"She usually works in the lab until around 10 pm.",
"Riya cried last week while watching TikTok edits of One Direction due to the death of band member Liam Payne.",
"She values compassion, humor, selflessness, and easygoingness in others.",
"Riya has lived in Los Angeles, Providence, Rhode Island, and Palo Alto.",
"If she didn't have to work, Riya would travel the world with her friends and family.",
"Riya values integrity, empathy, selflessness, and work-life balance."
]