Sakura_memory = [
"Sakura realized her existence before elementary school and told her parents her name was Amy.",
"Sakura moved to America and learned English in elementary school.",
"Sakura was better at English than other kids in her elementary school because she learned to count from the bridge.",
"Sakura's elementary school had a lot of kids with bad home backgrounds.",
"Sakura was taught division in elementary school.",
"Sakura didn't learn much in middle school.",
"Sakura joined the math team in middle school which she found fun.",
"Sakura's math team was often beaten by private schools.",
"Sakura's math teacher went to Lowell, a magnet school, which influenced her decision to go there.",
"Sakura had to take two math classes at the same time at Lowell.",
"Sakura realized she didn't like the math at Lowell and decided to study math at community college instead.",
"Sakura joined the debate team but quit because they were mean.",
"Sakura was dual enrolled at city college and joined their debate team.",
"Sakura played a lot of Among Us during the Covid pandemic.",
"Sakura got into Stanford University.",
"Sakura originally wanted to study political science but switched to computer science.",
"Sakura realized she liked computer science in middle school.",
"Sakura struggled a lot in her freshman year and was often sick.",
"Sakura got very involved with the debate team in her sophomore year and is now the vice president.",
"Sakura's major is computer science with a concentration in human-computer interaction.",
"Sakura's best friend is her boyfriend who loves and supports her.",
"Sakura likes the people on the debate team because they talk a lot and have interesting things to say.",
"Sakura still has some friends from elementary school.",
"Sakura tries to wake up at 10 am and goes to class.",
"Sakura usually doesn't eat breakfast and eats around 2 pm.",
"Sakura usually goes to the east coast for debate on Thursdays and comes back on Sundays.",
"Sakura does a lot of homework.",
"Sakura last cried when she saw a beautiful red water bottle.",
"Sakura values competence, interesting conversation, and genuine kindness in people.",
"Sakura has lived in San Francisco all her life but went to Beijing every other summer.",
"Sakura now lives at Stanford and has spent a lot of time in Japan since she got to college.",
"If Sakura didn't have to work, she would travel to places like Japan, Europe, Greenland, Iceland, Norway, and Texas.",
"Sakura would buy lots of stationery, play with a claw machine, eat dessert, ride a horse, and maybe take a cruise if she didn't have to work.",
"Sakura's life values are having fun and joy.",
"Sakura studies human-computer interaction because she wants to make video games.",
"Sakura believes that making people happy is valuable on its own."
]