Anwen_memory = [
"Anwen was born in North Carolina on the east coast and later moved to San Diego, California.",
"Anwen's mother was studying pharmacy and his father was working when he was born.",
"Anwen's father was his primary caretaker during his early years.",
"Anwen attended either preschool or kindergarten in San Diego, which was his first school experience.",
"Anwen participated in after school YMCA activities in San Diego and remembers experiencing forest fires.",
"Anwen suffered from eczema from a young age, which he struggled with until he was 22.",
"At the age of 5, Anwen moved to Texas due to cost of living and for his skin condition.",
"Anwen attended elementary school in Texas and lived in temporary housing before settling in a suburban neighborhood, Grand Prairie.",
"Anwen attended Dalton Elementary school in Grand Prairie and made many Asian friends.",
"Anwen was identified into the Gifted & Talented program in 2nd or 3rd grade.",
"Anwen had a difficult time in intermediate school, feeling alone and struggling to make new friends.",
"Anwen realized he was good at school during middle school and started forming more robust friendships.",
"Anwen's parents are immigrants from Vietnam, who immigrated after the war in the 1970s or 1980s.",
"Anwen's father immigrated to Kansas and his mother to Seattle, both were sponsored by the catholic church.",
"Anwen has a sister who is 3 years older than him.",
"Anwen's sister applied to Stanford for college but didn't get in, which made Anwen research about Stanford.",
"Anwen got into volunteering and joined a solar car club in high school.",
"Anwen was involved in a lot of science/math competitions in high school and was good at it.",
"Anwen's main interests in high school were chemistry, physics, and math.",
"Anwen initially thought he would major in EE at Stanford but switched to Product Design and then to CS, focusing on graphics.",
"Anwen worked at a startup for a year after graduation and then returned to Stanford for his masters in AI.",
"Anwen was involved in the AAPI community during his undergrad years.",
"Anwen's major for undergrad was CS - Graphics and for grad was CS - AI.",
"Anwen's friends from high school and college are important to him because they can all be there for each other and have a good time together.",
"Anwen lives off campus in South SF and commutes to Stanford.",
"Anwen tries to go to the gym at least 2-3 times a week.",
"Anwen and his partner usually cook dinners together and watch shows or movies in their free time.",
"Anwen last cried while rewatching the movie 'Everything Everywhere All At Once' on a plane.",
"Anwen values kindness, empathy, and uniqueness in other people.",
"Anwen has lived in North Carolina, Texas, and California.",
"If Anwen didn't have to work, he would do something along the lines of teaching and own personal work.",
"Anwen's life values include being a good person, constantly learning and improving, and giving back."
]