Camila_memory = [
"Camila was born in Costa Rica in 2001 and grew up there.",
"She moved to the US for college.",
"Camila's parents are both Costa Rican.",
"She is an only child but has a big extended family.",
"She attended an American school in Costa Rica.",
"Camila chose Stanford because of the IB program and her interest in studying psychology.",
"She didn't want to be a psychologist, but was interested in SymSys after seeing it in a Youtube video.",
"Camila is doing a Coterm in MS&E and has an Education minor.",
"She was initially intimidated by CS but came to love it, especially the interdisciplinary class.",
"Camila is unsure about her plans for next year but wants to work in tech.",
"One of her hobbies is ballet and she is currently in the cardinal ballet group.",
"Camila is majoring in SymSys in the HCAI track, and doing an MS in MS&E with an Education minor.",
"She has many friends scattered around and is heavily involved in the Latino community.",
"Camila values being able to speak Spanish and considers her friends her home away from home.",
"She was part of Stanford Women in Business during the Covid year and made close friends from various cultural backgrounds.",
"Camila values culture outside of the US.",
"She believes her friends will stick by her and be there for her unconditionally.",
"Camila wakes up at 7am and enjoys going to the Dish in the morning.",
"She often calls her mom or listens to a podcast or music in the morning.",
"Her daily routine includes classes, meals with friends, work, and journaling or reading before bed.",
"The last time Camila cried was while watching the movie 'Music of the Heart with Meryl Streep' for Educ101.",
"She values strong perspectives, openness, kindness, striving to be better, fun, and balance in other people.",
"Camila has lived in Costa Rica, Stanford for 4 years, Paris for 3 months, NY for 3 months, and SF for 3 months.",
"She did internships in NY and SF.",
"If she didn't have to work, Camila would dance in a ballet company, start a project, tinker with a tech product, and spend more time with family and reading.",
"Camila's life values are education, excellence, kindness, and purpose."
]