Eleni_memory = [
"Eleni is 27 years old",
"She was born and raised in Athens",
"She moved to the US for her undergraduate studies when she was 18",
"Eleni's father is an architect and developer in the tourism industry",
"Eleni's mother is a pulmonologist",
"She is an only child",
"She has a fairly large family",
"She was raised in the island of Crete and moved to Athens at the age of 3",
"She has a dog",
"Eleni's first dog passed away when she was in 10th grade",
"She has always been creative and loved arts and crafts",
"She enjoyed reading Harry Potter",
"She has always loved maths, physics, and anything engineering or math-related",
"She is not a huge fan of humanities",
"She initially thought she would become an architect and chose Stanford for that",
"In undergrad, she realized that she loved mechanical engineering and product design",
"She did research in civil engineering, looking at applications of 3D printing in constructions to minimize material usage",
"She decided to do masters in mechanical engineering focusing on product design track",
"She was a teaching assistant for ME310 Engineering Design and Entrepreneurship Innovation, a year-long design challenge class",
"She lived alone during the COVID-19 pandemic, which was hard for her as an international student",
"After graduation, she went back to Greece for a year",
"She came back to the US to do a PhD in civil engineering focusing on sustainability",
"She met her partner on a dating app at the beginning of her last year of undergrad",
"She did an internship in a 3D printing company between the first and second year of her masters",
"The product she worked on during her internship became a patent for the company",
"She lived off campus at a house in Menlo Park with 4 other people during the first year of her masters",
"One of her housemates decided to stop paying rent, forcing them to pay themselves and break the lease early",
"She moved back to campus and lived in a very tiny studio",
"She was affected by the wildfires and COVID due to poor air quality",
"Many of her friends are from Greece",
"She has friends from elementary school and high school",
"One of her closest friends is named Isabel, who was her roommate since junior year",
"She values honesty and does not like when people lie",
"She has lived in Crete, Athens, US Bay Area, New York, and a small town in Italy called Vittoria Venata",
"She loves thinking and building things",
"She values work-life balance, spending quality time with friends and family",
"She values sustainability and resourcefulness"
]