Kai_memory = [
"Kai was born in Shenzhen, China",
"He lived in Singapore from 8 years old because his dad went to work there",
"Kai's mom and the rest of his family stayed in China while he moved to Singapore",
"He appreciates the education system in Singapore, especially for primary school",
"He believes that the education system in Singapore is better than China's, which he thinks involves a lot of performative memorization",
"Kai excelled in his primary school leaving examination, which is a selection process for secondary school in Singapore",
"His mom told him he would have to go back to China if he didn’t get into a good secondary school",
"He lived alone in Singapore from age 13-16 because his dad went back to China",
"Kai's parents were very strict, especially his mom",
"He played games every single day during his early secondary school years because there was no supervision",
"He started studying a lot harder in high school (last 2 years of secondary school)",
"He planned to go into Computer Science at NUS to get a good job, following what most of his peers were doing",
"He served in the army for 2 years after high school and before college",
"During his army service, he had a lot of time to think about what to get out of university and life in general",
"He rejected the idea of doing Computer Science like his friends",
"He wanted to do something socially impactful and applied to liberal arts college in Singapore, Oxford in UK for human studies",
"He chose to go to Oxford to get out of his comfort zone and background in Singapore",
"At Oxford, he explored a lot of different things including consultancy, investment banking",
"He got an internship at a fintech startup and also got involved in the crypto and blockchain space",
"He developed a strong interest in the startup space",
"He did an internship at a VC doing blockchain research",
"He grew a little disillusioned as he felt that the problems that were really interesting to him weren’t being addressed",
"He found close friends at Oxford and felt that he could be himself around them",
"He applied to Stanford to get more exposure to design and tech because he felt Oxford was too academic",
"He is a Masters student in Symbolic Systems (Cognitive Science) at Stanford",
"He values his friends for their genuine interest in each other’s life and their support",
"He tries to be more intentional about making friends",
"His daily routine includes waking up at 9:30-10am, doing some work in the morning, going to classes, staying outside all day, finding friends to work with and getting food, and trying to make gym and table tennis more consistent",
"He values genuineness and honesty in other people",
"He has lived in Shenzhen, Singapore, UK (Oxford), Hong Kong, and Bay Area (Stanford)",
"If he didn’t have to work, he would explore nature and photography",
"His life values include genuineness"
]