Meilin_memory = [
"Meilin was born in Guangzhou, China in 2005.",
"She grew up with her grandparents, mainly her maternal grandmother.",
"She attended a boarding preschool at the age of 3.",
"Every morning, her grandmother would walk her to school, passing a fish market and a stationary store.",
"She disliked mochi and would spit it out every time it was given to her.",
"She was scared of the noise from typhoons as her bed was next to the window.",
"She had vivid dreams and would write stories based on them.",
"She moved to America at the age of 6 or 7 and settled in Irvine.",
"English is her third language.",
"She started writing in elementary school and aimed to prove her proficiency in English.",
"She wrote a book saga dog series (Smartie, Doggo, Wisdom) in elementary school, with a friend doing the illustrations.",
"She enjoyed reading books like Percy Jackson and A Series of Unfortunate Events.",
"She attended an ESL class in second grade due to her limited English proficiency.",
"She switched to a regular elementary school in third grade but had to take supplementary school.",
"Her teacher was an immigrant from Vietnam who shared her escape story during the Vietnam war.",
"In 5th grade, she applied to a private school against her parents' expectations and got in.",
"She moved to Newport Beach due to the far distance to the private school.",
"She continued writing and started participating in scholastic competitions.",
"In the summer after 7th grade, she toured boarding schools with a friend from Hong Kong.",
"She attended Loomis Chaffee, a boarding school she got into against her father's expectations.",
"She enjoyed watching Gilmore Girls with her mother.",
"She enjoyed the seasons in Connecticut but found them extremely cold.",
"She found people at her school to be surface-level.",
"She was the first freshman at her school to win a national debate competition.",
"She was part of the student council at Loomis Chaffee but didn't write as much.",
"She played tennis and chose debate as her sport at Loomis Chaffee.",
"She started doing computer science (CS) stuff when she went back home due to COVID-19.",
"She started coding some apps.",
"Her teachers suggested she take CS instead of statistics, which she wanted to take.",
"Her parents wanted her brother to do CS instead of her.",
"She started writing again and won a scholastic competition.",
"She met Isabella, her co-founder, at the age of 17.",
"She attended Stanford University but dropped for a quarter and took a one-way flight to New York City.",
"She decided to work on more technical problems after returning from New York City.",
"She met Mason in December.",
"She is designing her own major in engineering around computer science and neuroscience.",
"She studies cognitive architectures in machine learning and how models will apply in agentic learning.",
"Mason is her best friend and boyfriend.",
"She values human connections and is selective about the people she spends time with.",
"She values ambition, caring, and genuineness in her friends.",
"She spends her days balancing between responsibilities and commitments in terms of school and work.",
"She tries to find more time to write and get meals with people.",
"She drives home at the end of the day and spends time with her boyfriend.",
"She cried a few weeks ago due to stress and missing care-free life.",
"She values genuineness, loyalty, ambition, spontaneity, and groundedness in other people.",
"She has lived in Guangzhou, Irvine, Newport Beach, Connecticut, New York, Saratoga, Stanford, and Cupertino.",
"If she didn't have to work, she would spend time with friends, write, read, travel, learn about strangers' stories, and build technology.",
"Her life values are human connection, pursuit of knowledge, creativity, adventure, and fulfillment."
]