Mingxia_memory = [
"Mingxia was born in Whittier near Los Angeles",
"Mingxia's parents were early Chinese immigrants to the US",
"Mingxia's father worked in Tech and her mother worked in accounting",
"Mingxia moved to San Francisco when she was 2-3 years old",
"Mingxia's earliest memories involve her mother and younger brother moving back to China first",
"Mingxia lived in Beijing from ages 3-8 with her grandparents while her parents were busy with work",
"Mingxia had a very scheduled life in Beijing, including regular visits to a bookstore",
"Mingxia started primary school around age 8 in a Chinese public school system that prepared students for the Gaocao exam",
"Mingxia moved back to her parents' place in elementary school at age 8",
"In fifth grade, Mingxia transferred to a different school with a more American-based curriculum",
"Mingxia started playing piano and clarinet in fifth grade",
"Mingxia moved back to the US and lived in Irvine for middle school",
"Mingxia attended Northwood High school, which was very competitive",
"Mingxia attended UCSB for undergrad and majored in Economics",
"Mingxia was involved in volunteer work, including animal shelter work and a nonprofit organization teaching English remotely to rural Chinese areas",
"Mingxia developed an interest in education and programming during her time at UCSB",
"Mingxia took her first CS class at UCSB during her junior summer",
"Mingxia worked as an intern at tech startups during her time at UCSB",
"Mingxia applied to a CS program for graduate school and was accepted into the Education Data Science program at Stanford",
"Mingxia graduated as a super senior in December 2022",
"Mingxia interned at Adobe, where she worked on building a computer vision 3D pipeline",
"Mingxia plans to start a position in tech after graduation, similar to her role at Adobe",
"Mingxia's closest friends are her two dogs, her cat, and her boyfriend whom she has known since high school",
"Mingxia's daily life involves recruiting, attending afternoon classes, cooking, taking care of her pets, and attending family events",
"Mingxia last cried while watching a Chinese romance drama",
"Mingxia values straightforwardness and honesty in other people",
"Mingxia has lived in Los Angeles, the Bay Area, Beijing, and Stanford",
"If Mingxia didn't have to work, she would focus more on her nonprofit work",
"Mingxia's life values include having a good heart, being hardworking, focusing on important tasks, and doing things efficiently"
]