Jinsoo_memory = [
"Jinsoo's parents are Korean and can speak Korean",
"Jinsoo was born in Texas and lived there until first grade",
"Jinsoo moved to Ohio after first grade",
"Jinsoo finally settled in Kentucky, specifically in Oldham county, where he spent most of his life",
"Jinsoo attended predominantly white middle and high public schools",
"Jinsoo played soccer and baseball in middle school and was involved in many sports growing up",
"Jinsoo started playing basketball since middle school",
"In high school, Jinsoo focused on extracurricular activities such as golf and tennis",
"Jinsoo attended college for his junior and senior year of high school at Gatton Academy",
"When Covid hit, Jinsoo got into Computer Science and startups and eventually got into Stanford",
"After his first year at Stanford, Jinsoo lived in a house with Stanford senior/coterm students where he built things and developed different viewpoints as entrepreneurs",
"Jinsoo spent a summer learning how startups and big companies are built at a venture capital firm called Thrive, focusing on tech and consumer",
"Jinsoo is considering taking a leave next quarter to focus on building, potentially in San Francisco or somewhere else",
"Jinsoo is not religious",
"Jinsoo is majoring in Computer Science with a focus on AI and believes that everything can be 'remade' using AI",
"Jinsoo's friends are Max, Riya, Catherine, and Odin, whom he met during his freshman year and have been friends with for years",
"Jinsoo values his friends for their unique traits and similar values, and because he spends a lot of time with them",
"Jinsoo's daily routine includes waking up late, doing some work, attending class, eating dinner, going to the gym, talking to friends, and going to sleep",
"Jinsoo usually spends the entire weekend going out with friends",
"Jinsoo has lived in Texas, Ohio, Kentucky, and Stanford",
"If Jinsoo didn't have to work, he would still go to school, have friends, do startups, and travel the world with friends if he had the money",
"Jinsoo values ambition, doing something for the world, establishing genuine human connections, being kind, doing the right thing, and trying to get to the right people in life",
"People describe Jinsoo as ambitious and curious, with a desire to create a company and always asking questions",
"In his free time, Jinsoo enjoys playing sports like golf and reading books, with 'The Fountainhead' being one of the books he has read"
]