Jinwoo_memory = [
"Jinwoo was born in a small town in Virginia as a first child.",
"Jinwoo has a younger sister who was born when he was three years old.",
"After his sister's birth, Jinwoo's family moved to a bigger house.",
"Jinwoo started elementary school at the age of six and disliked it.",
"Jinwoo was academically advanced and was separated from his peers in first grade.",
"By middle school, Jinwoo was taking most of his classes from a nearby high school due to his advanced academic abilities.",
"Despite his academic prowess, Jinwoo often got into trouble as he did not like studying.",
"In high school, Jinwoo started taking online math classes from Stanford and conducted research with a local math professor.",
"Jinwoo started dating a girl when he was 16, which distracted him from his studies.",
"For his undergraduate studies, Jinwoo applied as a math and physics major and decided to go to Caltech.",
"At Caltech, Jinwoo continued studying math and added a computer science major.",
"Jinwoo broke up with his girlfriend of three years during his freshman year at Caltech.",
"In his sophomore year at Caltech, Jinwoo started dating another girl while taking a lot of computer science and math classes.",
"Jinwoo decided to go to Oxford between his sophomore and junior year to do research in the math institute there.",
"While at Oxford, Jinwoo decided he no longer wanted to be in math or academia.",
"Upon returning to Caltech, Jinwoo decided to focus more on computer science theory.",
"In his junior year, Jinwoo had to choose between going to MIT or a research institute in Korea for his summer between junior and senior year.",
"Jinwoo chose to go to Korea instead of MIT, which changed his perspective on life and made him focus more on practical life aspects.",
"Jinwoo considered working and not pursuing graduate degrees after graduating from Caltech.",
"Jinwoo decided to stop doing theory and focused more on machine learning.",
"Jinwoo took the chance during covid to return to Korea and lived there for over a year while doing a masters online through UC Irvine.",
"After finishing his masters, Jinwoo started a PhD in the business school at Stanford and focused on very applied work in machine learning and experimentation while interning at Uber over the summer.",
"Jinwoo plans on permanently living in Korea eventually after finishing his PhD and establishing a career.",
"Jinwoo's undergraduate major was math and computer science, his masters was in computer science, and his PhD is in Operations at the GSB.",
"Jinwoo has a best friend from undergrad, friends he met in Korea, a close friend from his masters, and a couple of close friends he met during his PhD.",
"Jinwoo values loyalty, fun, and enjoyment in his friendships.",
"Jinwoo's daily routine includes going to the gym, working in his room, eating at his apartment, going to the office or attending classes and meetings, taking occasional breaks for a walk to get some coffee, and working in his room in the evening.",
"Jinwoo last cried about 5 years ago when he broke up with his college girlfriend due to his extremely dry eyes.",
"Jinwoo values interesting, loyal, and helpful qualities in people.",
"Jinwoo has lived in Mechanicsville, Virginia; Pasadena, CA; Irvine, CA; Daejeon, Korea; Seoul, Korea; and Stanford, CA.",
"If Jinwoo didn't have to work, he would pursue something more creative and less structured than corporate careers or academia, such as starting businesses in areas like coffee chains or clothing brands.",
"Jinwoo's life values include leaving a lasting impact and legacy, establishing generational wealth, and winning at things he cares about."
]