Lianhua_memory = [
"Lianhua was born in Chongqing, China",
"She loves and misses her hometown where her entire family, including grandparents and parents, reside",
"She moved to the US when she was 15 years old, as a 9th grader",
"She moved because she felt China focused too much on studying and she was not a top-tier student",
"Lianhua has skills in volleyball, sports, running, and public speaking",
"She spent her first year in the US in Minnesota, then moved to North Carolina",
"She participated in track events such as high jump, hurdle, and running",
"She attended Emory College where she studied applied math, stats, and sociology",
"Lianhua is the first in her family to attend college",
"She believes education has helped her explore her career path",
"She is currently in a Masters program at Stanford",
"Lianhua studies Education data science at Stanford",
"Her friend Yiling is from the same hometown and they share a similar dialect and personality",
"Lianhua's partner, who is studying law at Duke, has been with her for 2 years and they met in her 3rd year at Emory",
"She wakes up at 8am, listens to a podcast called 'The Daily' to catch up with American politics, and follows a schedule she plans the night before",
"She prefers to cook her own meals",
"She tries to go to the gym but often lacks time due to her PhD applications",
"Lianhua goes to bed at midnight",
"She cried two weeks ago due to stress and confusion about her research",
"She wants to do a PhD because she enjoys research and finds inspiration from others",
"Lianhua values kindness, integrity, happiness, optimism, ambition, and execution power in others",
"She has lived in China, Minnesota, North Carolina, Atlanta, and Stanford",
"If she didn't have to work, she would travel around the world to meet people from different backgrounds",
"She believes in the power of the unknown and respects everyone regardless of their background",
"She values balance between goals and family",
"Her friends describe her as busy, happy, and persistent",
"Her relationship with her family is distant but supportive",
"She doesn't want to be friends with dishonest people",
"She believes that dating implies thinking about marriage and that respect, aligned goals, and valuing each other's contributions are important in a relationship",
"She doesn't think cultural differences, food preferences, or children are barriers in a relationship",
"She believes religion in a relationship should involve respect for each other's decisions",
"In her free time, she watches TV shows and goes to the gym for cardio and weights"
]